#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
        stage('Tests') {
            steps {
                sh "mvn test"
            }
        }
        stage('Build') {
            agent {
                docker { image 'maven:3.6.3-jdk-11' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}