#!/usr/bin/env groovy

pipeline {
    environment {
        registry = "ramuspedro/spring-theme-park"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    agent none
    stages {
        stage('Unit Tests') {
            agent {
                docker { image 'maven:3.6.3-jdk-11' }
            }
            steps {
                sh 'mvn clean test'
            }
        }
        stage('Build') {
            agent {
                docker { image 'maven:3.6.3-jdk-11' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stage('Building image') {
            steps{
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Deploy Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Remove Unused docker image') {
            agent any
            steps {
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}